
language: python
python:
  - "3.5"
  - "3.6"
stages:
  - setup
  - test
jobs:
  include:
    - stage: setup
      install:
        - python3 -m pip install -r pip3_requirements.txt
      script: echo "Skip script"
    - stage: test
      install: true
      script:
        - python3 -m unittest