
language: python
python:
  - "3.5"
  - "3.6"
stages:
  - test
  - docker

install:
  - python3 -m pip install -r pip3_requirements.txt
script:
  - python3 -m unittest


jobs:
  include:
    - stage: docker
      install:
      script: echo "Skip script"
      