FROM ubuntu:18.04

WORKDIR /workspace
COPY pip3_requirements.txt pip3_requirements.txt

RUN apt update && \
    apt install -y \
        python3.6 \
        python3-pip \
        && \
    rm -rf /var/lib/apt/lists
    
RUN pip3 install -r pip3_requirements.txt