# This is a basic workflow to help you get started with Actions

name: MergeCI

# Controls when the action will run. 
on:
  # Triggers on push (or merge) to main
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker-ubuntu:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Pull Image
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker pull ${{ secrets.DOCKERHUB_REPO }}/photo-location-plotter:latest

      - name: Build Image
        run: |
            cd docker/ubuntu
            docker build -t photo_location_plotter:latest -t ${{ secrets.DOCKERHUB_REPO }}/photo-location-plotter:latest --cache-from ${{ secrets.DOCKERHUB_REPO }}/photo-location-plotter -f Dockerfile.Ubuntu ../..
      
      - name: Push Image
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
            cd docker/ubuntu
            docker push ${{ secrets.DOCKERHUB_REPO }}/photo-location-plotter:latest
